name: codesaima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  easy_mask: ^2.0.1
  path_provider: ^2.0.9
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  fluent_ui: ^3.12.0
  localization: ^2.1.0
  pattern_formatter: ^2.0.0
  date_time_picker: ^2.1.0
  pdf: ^3.8.1
  share_plus: ^4.0.8
  change_app_package_name: ^1.1.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/