name: codesaima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  easy_mask: ^2.0.1
  flutter_easyloading: ^3.0.3
  path_provider: ^2.0.9
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  numberpicker: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/