// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9YlCu28oqP1CnzMZm6YqmtYnkAzE1Cdo',
    appId: '1:579904745965:web:6656ae83b79d05f7d237e4',
    messagingSenderId: '579904745965',
    projectId: 'codesaima-e47df',
    authDomain: 'codesaima-e47df.firebaseapp.com',
    storageBucket: 'codesaima-e47df.appspot.com',
    measurementId: 'G-6TL7962HSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAFyxaC-IPUWgf9Goegh_FOuHPHD7hiAs',
    appId: '1:579904745965:android:ff842eaba39bc0c9d237e4',
    messagingSenderId: '579904745965',
    projectId: 'codesaima-e47df',
    storageBucket: 'codesaima-e47df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lOVtHwsRTTuvG3wvkxT_Lc_lseYDrqA',
    appId: '1:579904745965:ios:6872544d0a5e682bd237e4',
    messagingSenderId: '579904745965',
    projectId: 'codesaima-e47df',
    storageBucket: 'codesaima-e47df.appspot.com',
    iosClientId: '579904745965-nqh179pmgj2met11sekm52h4hnqv480a.apps.googleusercontent.com',
    iosBundleId: 'com.example.codesaima',
  );
}
